version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vaccinationmain
      - SPRING_DATASOURCE_USERNAME=postgre
      - SPRING_DATASOURCE_PASSWORD=Admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_SQL_INIT_MODE=always
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=vaccinationmain
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=Admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
