version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "4200:4200"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/reservationVaccinationMain
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Admin
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reservationVaccinationMain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/src/main/resources/data-main.sql:/docker-entrypoint-initdb.d/01-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservationVaccinationMain"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data: