spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_vaccination
    username: postgres
    password: simone
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create